server:
  port: 8201
spring:
  cloud:
    config:
      server:
        git:
          # 这里填写的是本地仓库地址，远程仓库直接填写远程仓库地址 http://git...
          uri: https://github.com/Wahoyu/CloudStudy/blob/8d1fb53c195571c1a07b0f92fdeb558d5e40c3a9/config--server/src/main/resources/config-repo/bookservice-dev.yml
          # 默认分支设定为你自己本地或是远程分支的名称
          default-label: master
  application:
    name: bookservice
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloudstudy
#    username: root
#    password: 123456
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka
